import { describe, it, expect } from "vitest";
import {
  hasMontenegroVariantNote,
  extractStructuredMontenegroNote,
} from "../../convex/contentStudio/_validatorHelpers";

/**
 * The Montenegrin-pronunciation Ijekavian variant is no longer generated by
 * the Validator from a fixed word-pair table. It is written by Creator/Fixer
 * only when the Montenegrin-pronunciation skill is checked on the draft, and
 * only in this exact shape: "In Montenegro: <ijekavian form>." The Lector
 * checks it, and the Translator carries it verbatim into noteDe. These tests
 * cover the two helpers the Translator's vocabulary guard relies on to find
 * that line inside a possibly multi-line note.
 */
describe("hasMontenegroVariantNote (new skill-authored format)", () => {
  it("recognizes the structured sentence", () => {
    expect(hasMontenegroVariantNote("In Montenegro: gdje.")).toBe(true);
    expect(hasMontenegroVariantNote("In Montenegro: razumijem.")).toBe(true);
  });

  it("recognizes the line alongside other notes", () => {
    expect(
      hasMontenegroVariantNote("Chunk: fixed phrase, grammar explained later\nIn Montenegro: ne razumijem.")
    ).toBe(true);
    expect(hasMontenegroVariantNote("Gender: neuter; In Montenegro: mlijeko.")).toBe(true);
  });

  it("is false for notes without the line", () => {
    expect(hasMontenegroVariantNote("Gender: feminine")).toBe(false);
    expect(hasMontenegroVariantNote("")).toBe(false);
    expect(hasMontenegroVariantNote(undefined)).toBe(false);
  });
});

describe("extractStructuredMontenegroNote (new skill-authored format)", () => {
  it("extracts the line next to a Chunk note", () => {
    expect(
      extractStructuredMontenegroNote("Chunk: fixed phrase, grammar explained later\nIn Montenegro: ne razumijem.")
    ).toBe("In Montenegro: ne razumijem.");
  });

  it("extracts the line when notes are separated by ;", () => {
    expect(extractStructuredMontenegroNote("Gender: masculine; In Montenegro: hljeb.")).toBe(
      "In Montenegro: hljeb."
    );
  });

  it("returns null when the note has no Montenegro line", () => {
    expect(extractStructuredMontenegroNote("Gender: feminine")).toBeNull();
    expect(extractStructuredMontenegroNote("")).toBeNull();
  });
});
