// Comprehensive vocabulary list for all 27 units from "Step by Step Serbian 1"
export type VocabWord = {
  serbian: string;
  english: string;
  unit: number;
};

export const VOCABULARY: VocabWord[] = [
  // Unit 1 - Na aerodromu (At the airport)
  { serbian: "aerodrom", english: "airport", unit: 1 },
  { serbian: "pasoš", english: "passport", unit: 1 },
  { serbian: "karta", english: "ticket", unit: 1 },
  { serbian: "prtljag", english: "luggage", unit: 1 },
  { serbian: "dobar dan", english: "good day", unit: 1 },
  { serbian: "dobro jutro", english: "good morning", unit: 1 },
  { serbian: "dobro veče", english: "good evening", unit: 1 },
  { serbian: "laku noć", english: "good night", unit: 1 },
  { serbian: "hvala", english: "thank you", unit: 1 },
  { serbian: "molim", english: "please / you're welcome", unit: 1 },
  { serbian: "da", english: "yes", unit: 1 },
  { serbian: "ne", english: "no", unit: 1 },
  { serbian: "izvините", english: "excuse me", unit: 1 },
  { serbian: "zdravo", english: "hello / hi", unit: 1 },
  { serbian: "ćao", english: "bye", unit: 1 },
  { serbian: "doviđenja", english: "goodbye", unit: 1 },
  { serbian: "ja", english: "I", unit: 1 },
  { serbian: "ti", english: "you (informal)", unit: 1 },
  { serbian: "on", english: "he", unit: 1 },
  { serbian: "ona", english: "she", unit: 1 },
  { serbian: "ono", english: "it", unit: 1 },
  { serbian: "biti", english: "to be", unit: 1 },
  { serbian: "imati", english: "to have", unit: 1 },

  // Unit 2 - U hotelu (At the hotel)
  { serbian: "hotel", english: "hotel", unit: 2 },
  { serbian: "soba", english: "room", unit: 2 },
  { serbian: "ključ", english: "key", unit: 2 },
  { serbian: "rezervacija", english: "reservation", unit: 2 },
  { serbian: "noć", english: "night", unit: 2 },
  { serbian: "dan", english: "day", unit: 2 },
  { serbian: "recepcija", english: "reception", unit: 2 },
  { serbian: "kupatilo", english: "bathroom", unit: 2 },
  { serbian: "krevet", english: "bed", unit: 2 },
  { serbian: "tuš", english: "shower", unit: 2 },
  { serbian: "lift", english: "elevator", unit: 2 },
  { serbian: "doručak", english: "breakfast", unit: 2 },
  { serbian: "cena", english: "price", unit: 2 },
  { serbian: "slobodan", english: "free / available", unit: 2 },
  { serbian: "zauzet", english: "occupied / busy", unit: 2 },

  // Unit 3 - U kafiću (At the café)
  { serbian: "kafić", english: "café", unit: 3 },
  { serbian: "kafa", english: "coffee", unit: 3 },
  { serbian: "čaj", english: "tea", unit: 3 },
  { serbian: "voda", english: "water", unit: 3 },
  { serbian: "sok", english: "juice", unit: 3 },
  { serbian: "pivo", english: "beer", unit: 3 },
  { serbian: "vino", english: "wine", unit: 3 },
  { serbian: "mleko", english: "milk", unit: 3 },
  { serbian: "šećer", english: "sugar", unit: 3 },
  { serbian: "račun", english: "bill", unit: 3 },
  { serbian: "konobar", english: "waiter", unit: 3 },
  { serbian: "meni", english: "menu", unit: 3 },
  { serbian: "želeti", english: "to want / wish", unit: 3 },
  { serbian: "piti", english: "to drink", unit: 3 },

  // Unit 4 - Gde je...? (Where is...?)
  { serbian: "gde", english: "where", unit: 4 },
  { serbian: "ovde", english: "here", unit: 4 },
  { serbian: "tamo", english: "there", unit: 4 },
  { serbian: "ulica", english: "street", unit: 4 },
  { serbian: "trg", english: "square", unit: 4 },
  { serbian: "most", english: "bridge", unit: 4 },
  { serbian: "park", english: "park", unit: 4 },
  { serbian: "muzej", english: "museum", unit: 4 },
  { serbian: "pozorište", english: "theater", unit: 4 },
  { serbian: "bioskop", english: "cinema", unit: 4 },
  { serbian: "restoran", english: "restaurant", unit: 4 },
  { serbian: "banka", english: "bank", unit: 4 },
  { serbian: "pošta", english: "post office", unit: 4 },
  { serbian: "levo", english: "left", unit: 4 },
  { serbian: "desno", english: "right", unit: 4 },
  { serbian: "pravo", english: "straight", unit: 4 },
  { serbian: "blizu", english: "near", unit: 4 },
  { serbian: "daleko", english: "far", unit: 4 },

  // Unit 5 - Šta radiš? (What are you doing?)
  { serbian: "raditi", english: "to work / do", unit: 5 },
  { serbian: "učiti", english: "to learn / study", unit: 5 },
  { serbian: "čitati", english: "to read", unit: 5 },
  { serbian: "pisati", english: "to write", unit: 5 },
  { serbian: "govoriti", english: "to speak", unit: 5 },
  { serbian: "slušati", english: "to listen", unit: 5 },
  { serbian: "gledati", english: "to watch / look", unit: 5 },
  { serbian: "razumeti", english: "to understand", unit: 5 },
  { serbian: "znati", english: "to know", unit: 5 },
  { serbian: "moći", english: "can / to be able", unit: 5 },
  { serbian: "jezik", english: "language", unit: 5 },
  { serbian: "knjiga", english: "book", unit: 5 },
  { serbian: "novine", english: "newspaper", unit: 5 },
  { serbian: "časopis", english: "magazine", unit: 5 },
  { serbian: "film", english: "film / movie", unit: 5 },
  { serbian: "muzika", english: "music", unit: 5 },

  // Unit 6 - Koliko je sati? (What time is it?)
  { serbian: "sat", english: "hour / clock", unit: 6 },
  { serbian: "vreme", english: "time", unit: 6 },
  { serbian: "minut", english: "minute", unit: 6 },
  { serbian: "sekund", english: "second", unit: 6 },
  { serbian: "jutro", english: "morning", unit: 6 },
  { serbian: "podne", english: "noon", unit: 6 },
  { serbian: "popodne", english: "afternoon", unit: 6 },
  { serbian: "veče", english: "evening", unit: 6 },
  { serbian: "noć", english: "night", unit: 6 },
  { serbian: "rano", english: "early", unit: 6 },
  { serbian: "kasno", english: "late", unit: 6 },
  { serbian: "sada", english: "now", unit: 6 },
  { serbian: "danas", english: "today", unit: 6 },
  { serbian: "sutra", english: "tomorrow", unit: 6 },
  { serbian: "juče", english: "yesterday", unit: 6 },

  // Unit 7 - Dogovor (Making arrangements)
  { serbian: "dogovor", english: "arrangement / agreement", unit: 7 },
  { serbian: "sastanak", english: "meeting", unit: 7 },
  { serbian: "poziv", english: "invitation", unit: 7 },
  { serbian: "ponedeljak", english: "Monday", unit: 7 },
  { serbian: "utorak", english: "Tuesday", unit: 7 },
  { serbian: "sreda", english: "Wednesday", unit: 7 },
  { serbian: "četvrtak", english: "Thursday", unit: 7 },
  { serbian: "petak", english: "Friday", unit: 7 },
  { serbian: "subota", english: "Saturday", unit: 7 },
  { serbian: "nedelja", english: "Sunday", unit: 7 },
  { serbian: "nedelja", english: "week", unit: 7 },
  { serbian: "vikend", english: "weekend", unit: 7 },
  { serbian: "slobodan", english: "free (time)", unit: 7 },

  // Unit 8 - U restoranu (In the restaurant)
  { serbian: "restoran", english: "restaurant", unit: 8 },
  { serbian: "meni", english: "menu", unit: 8 },
  { serbian: "jelo", english: "dish / meal", unit: 8 },
  { serbian: "predjelo", english: "appetizer", unit: 8 },
  { serbian: "glavno jelo", english: "main course", unit: 8 },
  { serbian: "desert", english: "dessert", unit: 8 },
  { serbian: "supa", english: "soup", unit: 8 },
  { serbian: "salata", english: "salad", unit: 8 },
  { serbian: "meso", english: "meat", unit: 8 },
  { serbian: "riba", english: "fish", unit: 8 },
  { serbian: "piletina", english: "chicken", unit: 8 },
  { serbian: "svinjetina", english: "pork", unit: 8 },
  { serbian: "govedina", english: "beef", unit: 8 },
  { serbian: "hleb", english: "bread", unit: 8 },
  { serbian: "pirinač", english: "rice", unit: 8 },
  { serbian: "krompir", english: "potato", unit: 8 },
  { serbian: "povrće", english: "vegetables", unit: 8 },
  { serbian: "voće", english: "fruit", unit: 8 },
  { serbian: "ukusan", english: "delicious / tasty", unit: 8 },
  { serbian: "jesti", english: "to eat", unit: 8 },

  // Unit 9 - Tipičan dan (Daily routine)
  { serbian: "ustati", english: "to get up", unit: 9 },
  { serbian: "umiti se", english: "to wash oneself", unit: 9 },
  { serbian: "obući se", english: "to get dressed", unit: 9 },
  { serbian: "doručkovati", english: "to have breakfast", unit: 9 },
  { serbian: "ići", english: "to go", unit: 9 },
  { serbian: "posao", english: "work / job", unit: 9 },
  { serbian: "ručati", english: "to have lunch", unit: 9 },
  { serbian: "ručak", english: "lunch", unit: 9 },
  { serbian: "večerati", english: "to have dinner", unit: 9 },
  { serbian: "večera", english: "dinner", unit: 9 },
  { serbian: "odmarati se", english: "to rest", unit: 9 },
  { serbian: "spavati", english: "to sleep", unit: 9 },
  { serbian: "svaki dan", english: "every day", unit: 9 },
  { serbian: "obično", english: "usually", unit: 9 },
  { serbian: "ponekad", english: "sometimes", unit: 9 },
  { serbian: "uvek", english: "always", unit: 9 },
  { serbian: "nikad", english: "never", unit: 9 },

  // Unit 10 - Porodica (Family)
  { serbian: "porodica", english: "family", unit: 10 },
  { serbian: "otac", english: "father", unit: 10 },
  { serbian: "majka", english: "mother", unit: 10 },
  { serbian: "sin", english: "son", unit: 10 },
  { serbian: "kćerka", english: "daughter", unit: 10 },
  { serbian: "brat", english: "brother", unit: 10 },
  { serbian: "sestra", english: "sister", unit: 10 },
  { serbian: "deda", english: "grandfather", unit: 10 },
  { serbian: "baba", english: "grandmother", unit: 10 },
  { serbian: "muž", english: "husband", unit: 10 },
  { serbian: "žena", english: "wife / woman", unit: 10 },
  { serbian: "dete", english: "child", unit: 10 },
  { serbian: "deca", english: "children", unit: 10 },
  { serbian: "roditelji", english: "parents", unit: 10 },
  { serbian: "rođak", english: "relative", unit: 10 },
  { serbian: "prijatelj", english: "friend (male)", unit: 10 },
  { serbian: "prijateljica", english: "friend (female)", unit: 10 },

  // Unit 11 - Ljudi (People)
  { serbian: "čovek", english: "man / person", unit: 11 },
  { serbian: "ljudi", english: "people", unit: 11 },
  { serbian: "muškarac", english: "man", unit: 11 },
  { serbian: "žena", english: "woman", unit: 11 },
  { serbian: "mlad", english: "young", unit: 11 },
  { serbian: "star", english: "old", unit: 11 },
  { serbian: "visok", english: "tall", unit: 11 },
  { serbian: "nizak", english: "short (height)", unit: 11 },
  { serbian: "lep", english: "beautiful / handsome", unit: 11 },
  { serbian: "ružan", english: "ugly", unit: 11 },
  { serbian: "pametan", english: "smart / clever", unit: 11 },
  { serbian: "glup", english: "stupid", unit: 11 },
  { serbian: "dobar", english: "good", unit: 11 },
  { serbian: "loš", english: "bad", unit: 11 },
  { serbian: "ljubazan", english: "kind / polite", unit: 11 },
  { serbian: "zanimanje", english: "occupation / profession", unit: 11 },
  { serbian: "hobi", english: "hobby", unit: 11 },
  { serbian: "sport", english: "sport", unit: 11 },

  // Unit 12 - Narodi i jezici (Nationalities and languages)
  { serbian: "narod", english: "nation / people", unit: 12 },
  { serbian: "zemlja", english: "country / land", unit: 12 },
  { serbian: "grad", english: "city", unit: 12 },
  { serbian: "Srbija", english: "Serbia", unit: 12 },
  { serbian: "Srbijanac", english: "Serbian (male)", unit: 12 },
  { serbian: "Srbijanka", english: "Serbian (female)", unit: 12 },
  { serbian: "srpski", english: "Serbian (language/adj)", unit: 12 },
  { serbian: "Engleska", english: "England", unit: 12 },
  { serbian: "Englez", english: "Englishman", unit: 12 },
  { serbian: "Engleskinja", english: "Englishwoman", unit: 12 },
  { serbian: "engleski", english: "English (language/adj)", unit: 12 },
  { serbian: "Nemačka", english: "Germany", unit: 12 },
  { serbian: "Nemac", english: "German (male)", unit: 12 },
  { serbian: "Nemicа", english: "German (female)", unit: 12 },
  { serbian: "nemački", english: "German (language/adj)", unit: 12 },
  { serbian: "Francuska", english: "France", unit: 12 },
  { serbian: "Italija", english: "Italy", unit: 12 },
  { serbian: "Rusija", english: "Russia", unit: 12 },
  { serbian: "Amerika", english: "America", unit: 12 },

  // Unit 13 - Kako je bilo juče? (How was it yesterday?)
  { serbian: "juče", english: "yesterday", unit: 13 },
  { serbian: "prekjuče", english: "day before yesterday", unit: 13 },
  { serbian: "prošle nedelje", english: "last week", unit: 13 },
  { serbian: "prošlog meseca", english: "last month", unit: 13 },
  { serbian: "prošle godine", english: "last year", unit: 13 },
  { serbian: "bio", english: "was (male)", unit: 13 },
  { serbian: "bila", english: "was (female)", unit: 13 },
  { serbian: "bilo", english: "was (neuter)", unit: 13 },
  { serbian: "išao", english: "went (male)", unit: 13 },
  { serbian: "išla", english: "went (female)", unit: 13 },
  { serbian: "video", english: "saw (male)", unit: 13 },
  { serbian: "videla", english: "saw (female)", unit: 13 },
  { serbian: "rekao", english: "said (male)", unit: 13 },
  { serbian: "rekla", english: "said (female)", unit: 13 },

  // Unit 14 - Vreme (Weather)
  { serbian: "vreme", english: "weather / time", unit: 14 },
  { serbian: "sunce", english: "sun", unit: 14 },
  { serbian: "kiša", english: "rain", unit: 14 },
  { serbian: "sneg", english: "snow", unit: 14 },
  { serbian: "vetar", english: "wind", unit: 14 },
  { serbian: "oblak", english: "cloud", unit: 14 },
  { serbian: "temperatura", english: "temperature", unit: 14 },
  { serbian: "toplo", english: "warm / hot", unit: 14 },
  { serbian: "hladno", english: "cold", unit: 14 },
  { serbian: "lepo", english: "nice / beautiful", unit: 14 },
  { serbian: "loše", english: "bad", unit: 14 },
  { serbian: "proleće", english: "spring", unit: 14 },
  { serbian: "leto", english: "summer", unit: 14 },
  { serbian: "jesen", english: "autumn / fall", unit: 14 },
  { serbian: "zima", english: "winter", unit: 14 },
  { serbian: "januar", english: "January", unit: 14 },
  { serbian: "februar", english: "February", unit: 14 },
  { serbian: "mart", english: "March", unit: 14 },
  { serbian: "april", english: "April", unit: 14 },
  { serbian: "maj", english: "May", unit: 14 },
  { serbian: "jun", english: "June", unit: 14 },
  { serbian: "jul", english: "July", unit: 14 },
  { serbian: "avgust", english: "August", unit: 14 },
  { serbian: "septembar", english: "September", unit: 14 },
  { serbian: "oktobar", english: "October", unit: 14 },
  { serbian: "novembar", english: "November", unit: 14 },
  { serbian: "decembar", english: "December", unit: 14 },
  { serbian: "sever", english: "north", unit: 14 },
  { serbian: "jug", english: "south", unit: 14 },
  { serbian: "istok", english: "east", unit: 14 },
  { serbian: "zapad", english: "west", unit: 14 },

  // Unit 15 - Kako, s kim i kada putujete? (How, with whom and when do you travel?)
  { serbian: "putovati", english: "to travel", unit: 15 },
  { serbian: "putovanje", english: "journey / trip", unit: 15 },
  { serbian: "avion", english: "airplane", unit: 15 },
  { serbian: "voz", english: "train", unit: 15 },
  { serbian: "autobus", english: "bus", unit: 15 },
  { serbian: "auto", english: "car", unit: 15 },
  { serbian: "taksi", english: "taxi", unit: 15 },
  { serbian: "bicikl", english: "bicycle", unit: 15 },
  { serbian: "brod", english: "ship / boat", unit: 15 },
  { serbian: "stanica", english: "station", unit: 15 },
  { serbian: "voziti", english: "to drive", unit: 15 },
  { serbian: "leteti", english: "to fly", unit: 15 },
  { serbian: "brzo", english: "fast / quickly", unit: 15 },
  { serbian: "sporo", english: "slow / slowly", unit: 15 },
  { serbian: "sa", english: "with", unit: 15 },
  { serbian: "bez", english: "without", unit: 15 },

  // Unit 16 - Stivov novi stan (Steve's new apartment)
  { serbian: "stan", english: "apartment", unit: 16 },
  { serbian: "kuća", english: "house", unit: 16 },
  { serbian: "sprat", english: "floor / storey", unit: 16 },
  { serbian: "dnevna soba", english: "living room", unit: 16 },
  { serbian: "spavaća soba", english: "bedroom", unit: 16 },
  { serbian: "kuhinja", english: "kitchen", unit: 16 },
  { serbian: "trpezarija", english: "dining room", unit: 16 },
  { serbian: "kupatilo", english: "bathroom", unit: 16 },
  { serbian: "balkon", english: "balcony", unit: 16 },
  { serbian: "prozor", english: "window", unit: 16 },
  { serbian: "vrata", english: "door", unit: 16 },
  { serbian: "sto", english: "table", unit: 16 },
  { serbian: "stolica", english: "chair", unit: 16 },
  { serbian: "fotelja", english: "armchair", unit: 16 },
  { serbian: "kauč", english: "couch / sofa", unit: 16 },
  { serbian: "krevet", english: "bed", unit: 16 },
  { serbian: "orman", english: "wardrobe / closet", unit: 16 },
  { serbian: "polica", english: "shelf", unit: 16 },
  { serbian: "tepih", english: "carpet / rug", unit: 16 },
  { serbian: "lampa", english: "lamp", unit: 16 },
  { serbian: "slika", english: "picture / painting", unit: 16 },

  // Unit 17 - Telefonski razgovor (Telephone conversation)
  { serbian: "telefon", english: "telephone", unit: 17 },
  { serbian: "mobilni", english: "mobile phone", unit: 17 },
  { serbian: "poziv", english: "call", unit: 17 },
  { serbian: "poruka", english: "message", unit: 17 },
  { serbian: "broj", english: "number", unit: 17 },
  { serbian: "zvati", english: "to call", unit: 17 },
  { serbian: "odgovoriti", english: "to answer", unit: 17 },
  { serbian: "slušati", english: "to listen", unit: 17 },
  { serbian: "čuti", english: "to hear", unit: 17 },
  { serbian: "javiti se", english: "to get in touch", unit: 17 },
  { serbian: "halo", english: "hello (on phone)", unit: 17 },
  { serbian: "trenutak", english: "moment", unit: 17 },
  { serbian: "zauzeto", english: "busy (phone line)", unit: 17 },

  // Unit 18 - Stiv planira vikend (Planning a weekend)
  { serbian: "plan", english: "plan", unit: 18 },
  { serbian: "planirati", english: "to plan", unit: 18 },
  { serbian: "hteti", english: "to want", unit: 18 },
  { serbian: "hoću", english: "I will / I want", unit: 18 },
  { serbian: "nećу", english: "I won't", unit: 18 },
  { serbian: "izlet", english: "trip / excursion", unit: 18 },
  { serbian: "piknik", english: "picnic", unit: 18 },
  { serbian: "šetnja", english: "walk", unit: 18 },
  { serbian: "kupovina", english: "shopping", unit: 18 },
  { serbian: "bioskop", english: "cinema", unit: 18 },
  { serbian: "koncert", english: "concert", unit: 18 },
  { serbian: "zabava", english: "party / fun", unit: 18 },

  // Unit 19 - Srećan rođendan! (Happy birthday!)
  { serbian: "rođendan", english: "birthday", unit: 19 },
  { serbian: "srećan", english: "happy", unit: 19 },
  { serbian: "proslava", english: "celebration", unit: 19 },
  { serbian: "poklon", english: "gift / present", unit: 19 },
  { serbian: "torta", english: "cake", unit: 19 },
  { serbian: "svećа", english: "candle", unit: 19 },
  { serbian: "gost", english: "guest", unit: 19 },
  { serbian: "zabava", english: "party", unit: 19 },
  { serbian: "čestitati", english: "to congratulate", unit: 19 },
  { serbian: "slaviti", english: "to celebrate", unit: 19 },
  { serbian: "datum", english: "date", unit: 19 },
  { serbian: "godina", english: "year", unit: 19 },
  { serbian: "mesec", english: "month", unit: 19 },

  // Unit 20 - Kod lekara (Health matters)
  { serbian: "lekar", english: "doctor", unit: 20 },
  { serbian: "bolnica", english: "hospital", unit: 20 },
  { serbian: "apoteka", english: "pharmacy", unit: 20 },
  { serbian: "lek", english: "medicine / drug", unit: 20 },
  { serbian: "bolest", english: "illness / disease", unit: 20 },
  { serbian: "boleti", english: "to hurt / ache", unit: 20 },
  { serbian: "boli me", english: "it hurts me", unit: 20 },
  { serbian: "glava", english: "head", unit: 20 },
  { serbian: "oko", english: "eye", unit: 20 },
  { serbian: "uvo", english: "ear", unit: 20 },
  { serbian: "nos", english: "nose", unit: 20 },
  { serbian: "usta", english: "mouth", unit: 20 },
  { serbian: "zub", english: "tooth", unit: 20 },
  { serbian: "grlo", english: "throat", unit: 20 },
  { serbian: "stomak", english: "stomach", unit: 20 },
  { serbian: "ruka", english: "hand / arm", unit: 20 },
  { serbian: "noga", english: "leg / foot", unit: 20 },
  { serbian: "srce", english: "heart", unit: 20 },
  { serbian: "temperatura", english: "temperature / fever", unit: 20 },
  { serbian: "prehlada", english: "cold (illness)", unit: 20 },
  { serbian: "grip", english: "flu", unit: 20 },

  // Unit 21 - Boje i odeća (Colors and Clothes)
  { serbian: "boja", english: "color", unit: 21 },
  { serbian: "beo", english: "white", unit: 21 },
  { serbian: "crn", english: "black", unit: 21 },
  { serbian: "crven", english: "red", unit: 21 },
  { serbian: "plav", english: "blue", unit: 21 },
  { serbian: "zelen", english: "green", unit: 21 },
  { serbian: "žut", english: "yellow", unit: 21 },
  { serbian: "narandžast", english: "orange", unit: 21 },
  { serbian: "ljubičast", english: "purple", unit: 21 },
  { serbian: "siv", english: "gray", unit: 21 },
  { serbian: "braon", english: "brown", unit: 21 },
  { serbian: "odeća", english: "clothes", unit: 21 },
  { serbian: "košulja", english: "shirt", unit: 21 },
  { serbian: "majica", english: "T-shirt", unit: 21 },
  { serbian: "pantalone", english: "pants / trousers", unit: 21 },
  { serbian: "farmerke", english: "jeans", unit: 21 },
  { serbian: "suknja", english: "skirt", unit: 21 },
  { serbian: "haljina", english: "dress", unit: 21 },
  { serbian: "jakna", english: "jacket", unit: 21 },
  { serbian: "kaput", english: "coat", unit: 21 },
  { serbian: "cipele", english: "shoes", unit: 21 },
  { serbian: "patike", english: "sneakers", unit: 21 },
  { serbian: "čizme", english: "boots", unit: 21 },
  { serbian: "nositi", english: "to wear / carry", unit: 21 },

  // Unit 22 - Šta je bolje? (What's better?)
  { serbian: "bolji", english: "better", unit: 22 },
  { serbian: "najbolji", english: "best", unit: 22 },
  { serbian: "gori", english: "worse", unit: 22 },
  { serbian: "najgori", english: "worst", unit: 22 },
  { serbian: "veći", english: "bigger", unit: 22 },
  { serbian: "najveći", english: "biggest", unit: 22 },
  { serbian: "manji", english: "smaller", unit: 22 },
  { serbian: "najmanji", english: "smallest", unit: 22 },
  { serbian: "viši", english: "taller", unit: 22 },
  { serbian: "niži", english: "shorter", unit: 22 },
  { serbian: "lepši", english: "more beautiful", unit: 22 },
  { serbian: "najlepši", english: "most beautiful", unit: 22 },
  { serbian: "jeftiniji", english: "cheaper", unit: 22 },
  { serbian: "skuplji", english: "more expensive", unit: 22 },
  { serbian: "brži", english: "faster", unit: 22 },
  { serbian: "sporiji", english: "slower", unit: 22 },

  // Unit 23 - Kako izgledaju? (How do they look like?)
  { serbian: "izgled", english: "appearance / look", unit: 23 },
  { serbian: "izgledati", english: "to look / appear", unit: 23 },
  { serbian: "kosa", english: "hair", unit: 23 },
  { serbian: "oči", english: "eyes", unit: 23 },
  { serbian: "plav", english: "blond", unit: 23 },
  { serbian: "crn", english: "black (hair)", unit: 23 },
  { serbian: "smeđ", english: "brown (hair)", unit: 23 },
  { serbian: "kratak", english: "short", unit: 23 },
  { serbian: "dug", english: "long", unit: 23 },
  { serbian: "debeo", english: "fat / thick", unit: 23 },
  { serbian: "mršav", english: "thin / skinny", unit: 23 },
  { serbian: "lep", english: "beautiful / handsome", unit: 23 },
  { serbian: "ružan", english: "ugly", unit: 23 },
  { serbian: "mlad", english: "young", unit: 23 },
  { serbian: "star", english: "old", unit: 23 },

  // Unit 24 - Poseta (Visiting places)
  { serbian: "poseta", english: "visit", unit: 24 },
  { serbian: "posetiti", english: "to visit", unit: 24 },
  { serbian: "turista", english: "tourist", unit: 24 },
  { serbian: "turizam", english: "tourism", unit: 24 },
  { serbian: "znamenitost", english: "landmark / sight", unit: 24 },
  { serbian: "crkva", english: "church", unit: 24 },
  { serbian: "tvrđava", english: "fortress", unit: 24 },
  { serbian: "zamak", english: "castle", unit: 24 },
  { serbian: "spomenik", english: "monument", unit: 24 },
  { serbian: "fotografija", english: "photograph", unit: 24 },
  { serbian: "fotografisati", english: "to photograph", unit: 24 },
  { serbian: "razgledati", english: "to sightsee", unit: 24 },

  // Unit 25 - (Ne)običan dan ((Un)usual day)
  { serbian: "običan", english: "usual / ordinary", unit: 25 },
  { serbian: "neobičan", english: "unusual", unit: 25 },
  { serbian: "događaj", english: "event", unit: 25 },
  { serbian: "desiti se", english: "to happen", unit: 25 },
  { serbian: "početi", english: "to begin / start", unit: 25 },
  {serbian: "završiti", english: "to finish / end", unit: 25 },
  { serbian: "nastaviti", english: "to continue", unit: 25 },
  { serbian: "prestati", english: "to stop", unit: 25 },
  { serbian: "uspeti", english: "to succeed", unit: 25 },
  { serbian: "probati", english: "to try", unit: 25 },

  // Unit 26 - Iznenađenje (Surprise)
  { serbian: "iznenađenje", english: "surprise", unit: 26 },
  { serbian: "iznenaditi", english: "to surprise", unit: 26 },
  { serbian: "doći", english: "to come / arrive", unit: 26 },
  { serbian: "otići", english: "to leave / go away", unit: 26 },
  { serbian: "ući", english: "to enter", unit: 26 },
  { serbian: "izaći", english: "to exit / go out", unit: 26 },
  { serbian: "proći", english: "to pass", unit: 26 },
  { serbian: "preći", english: "to cross", unit: 26 },
  { serbian: "doneti", english: "to bring", unit: 26 },
  { serbian: "odneti", english: "to take away", unit: 26 },

  // Unit 27 - Šta ćeš raditi sutra? (What will you do tomorrow?)
  { serbian: "sutra", english: "tomorrow", unit: 27 },
  { serbian: "prekosutra", english: "day after tomorrow", unit: 27 },
  { serbian: "sledeće nedelje", english: "next week", unit: 27 },
  { serbian: "sledećeg meseca", english: "next month", unit: 27 },
  { serbian: "sledeće godine", english: "next year", unit: 27 },
  { serbian: "uskoro", english: "soon", unit: 27 },
  { serbian: "kasnije", english: "later", unit: 27 },
  { serbian: "možda", english: "maybe / perhaps", unit: 27 },
  { serbian: "sigurno", english: "certainly / surely", unit: 27 },
  { serbian: "verovatno", english: "probably", unit: 27 },
  { serbian: "nadam se", english: "I hope", unit: 27 },
];
